In [1]:
from firebird import aardvark as av

In [2]:
from test import fixtures as fx

In [3]:
bands = ('blue', 'cfmask', 'green', 'nir', 'red', 'swir1', 'swir2', 'thermal')

In [4]:
# retrieve chips and specs
for band in bands:
    globals()[band+'_specs'] = fx.chip_specs(band)
    globals()[band+'_chips'] = av.sort([i for i in fx.chips(band)])
    globals()[band+'_dates'] = av.dates(globals()[band+'_chips'])

In [5]:
print("chip <band>_chips keys: {}\n".format(blue_chips[0].keys()))
print("spec <band>_specs keys: {}\n".format(blue_specs[0].keys()))

chip <band>_chips keys: dict_keys(['y', 'data', 'x', 'acquired', 'ubid', 'source'])

spec <band>_specs keys: dict_keys(['wkt', 'band_product', 'instrument', 'pixel_x', 'chip_y', 'data_shape', 'data_mask', 'satellite', 'band_name', 'band_short_name', 'shift_y', 'resample_method', 'shift_x', 'band_long_name', 'data_type', 'name', 'ubid', 'band_category', 'pixel_y', 'data_range', 'data_units', 'data_fill', 'band_spectrum', 'chip_x', 'data_scale', 'tags'])



In [6]:
shared_dates = av.intersection([globals()[i+'_dates'] for i in bands])

In [7]:
# trim our band chips to the shared dates
for band in bands:
    globals()[band+"_trimmed"] = av.trim(globals()[band+"_chips"], shared_dates)

In [8]:
len(blue_trimmed) == len(shared_dates)

True

In [9]:
# numpy'd chips
for band in bands:    
    globals()[band+"_numpy"] = [i for i in av.to_numpy(globals()[band+"_trimmed"], av.byubid(globals()[band+"_specs"]))]

In [10]:
blue_numpy

[{'acquired': '2015-12-26T06:00:00Z',
  'data': array([[ 8452,  8459,  8368, ...,  8257,  8252,  8270],
         [ 8380,  8413,  8403, ...,  8307,  8271,  8212],
         [ 8525,  8511,  8458, ...,  8299,  8359,  8288],
         ..., 
         [ 8293,  8275,  8279, ..., -9999, -9999, -9999],
         [ 8210,  8278,  8251, ..., -9999, -9999, -9999],
         [ 8212,  8219,  8233, ..., -9999, -9999, -9999]], dtype=int16),
  'source': 'LE070440282015360-SC20161229030315',
  'ubid': 'LANDSAT_7/ETM/sr_band1',
  'x': -1821585,
  'y': 2891805},
 {'acquired': '2015-12-10T06:00:00Z',
  'data': array([[ 3687,  3678,  3513, ...,  1738,  1674,  1707],
         [ 3887,  3758,  3690, ...,  1829,  1677,  1609],
         [ 4091,  3912,  3811, ...,  1812,  1614,  1582],
         ..., 
         [ 5038,  5008,  4993, ..., -9999, -9999, -9999],
         [ 5144,  5062,  5149, ..., -9999, -9999, -9999],
         [ 5248,  5161,  5064, ..., -9999, -9999, -9999]], dtype=int16),
  'source': 'LE070440282015344-S

In [13]:
# rods
for band in bands:
    globals()[band+"_rods"] = av.rods(globals()[band+"_numpy"])


In [14]:
blue_rods

array([[[ 8452,  3687,  6506, ...,  1400,  4912,   612],
        [ 8380,  3887,  6472, ...,  1353,  4760,   618],
        [ 8525,  4091,  6622, ...,  1343,  4839,   638],
        ..., 
        [ 8293,  5038, -9999, ...,  1316,  5228,   690],
        [ 8210,  5144, -9999, ...,  1392,  5238,   708],
        [ 8212,  5248, -9999, ...,  1301,  5319,   694]],

       [[ 8459,  3678,  6587, ...,  1458,  4797,   637],
        [ 8413,  3758,  6451, ...,  1365,  4759,   611],
        [ 8511,  3912,  6386, ...,  1399,  4863,   574],
        ..., 
        [ 8275,  5008, -9999, ...,  1240,  5312,   659],
        [ 8278,  5062, -9999, ...,  1383,  5327,   666],
        [ 8219,  5161, -9999, ...,  1320,  5304,   618]],

       [[ 8368,  3513,  6523, ...,  1560,  4782,   741],
        [ 8403,  3690,  6386, ...,  1433,  4782,   689],
        [ 8458,  3811,  6316, ...,  1432,  4897,   599],
        ..., 
        [ 8279,  4993, -9999, ...,  1140,  5427,   568],
        [ 8251,  5149, -9999, ...,  1330, 

In [15]:
from firebird import chip

In [19]:
locs = chip.locations(blue_specs[0]['chip_x'], blue_specs[0]['chip_y'], blue_specs[0])

In [24]:
locs

array([[[ 3000., -3000.],
        [ 3000., -3030.],
        [ 3000., -3060.],
        ..., 
        [ 3000., -5910.],
        [ 3000., -5940.],
        [ 3000., -5970.]],

       [[ 3030., -3000.],
        [ 3030., -3030.],
        [ 3030., -3060.],
        ..., 
        [ 3030., -5910.],
        [ 3030., -5940.],
        [ 3030., -5970.]],

       [[ 3060., -3000.],
        [ 3060., -3030.],
        [ 3060., -3060.],
        ..., 
        [ 3060., -5910.],
        [ 3060., -5940.],
        [ 3060., -5970.]],

       ..., 
       [[ 5910., -3000.],
        [ 5910., -3030.],
        [ 5910., -3060.],
        ..., 
        [ 5910., -5910.],
        [ 5910., -5940.],
        [ 5910., -5970.]],

       [[ 5940., -3000.],
        [ 5940., -3030.],
        [ 5940., -3060.],
        ..., 
        [ 5940., -5910.],
        [ 5940., -5940.],
        [ 5940., -5970.]],

       [[ 5970., -3000.],
        [ 5970., -3030.],
        [ 5970., -3060.],
        ..., 
        [ 5970., -5910.],
        [

In [20]:
assc = av.assoc(locs, blue_rods)

In [21]:
assc

{(5400.0,
  -5520.0): array([-9999, -9999,  5525, ...,  1382,  4599,   721], dtype=int16),
 (4020.0,
  -3750.0): array([-9999, -9999,  6159, ...,  1388,  4575,   551], dtype=int16),
 (5130.0,
  -5250.0): array([ 8167, -9999,  5193, ...,  1392,  5303,   669], dtype=int16),
 (4350.0,
  -3840.0): array([ 8282, -9999,  6266, ...,  1277,  4674,   664], dtype=int16),
 (4170.0,
  -3990.0): array([-9999, -9999,  5775, ...,  1549,  4916,   680], dtype=int16),
 (5940.0,
  -5010.0): array([-9999,  4423,  5491, ...,  1245,  4405,   726], dtype=int16),
 (4920.0,
  -5850.0): array([ 8315,  5289, -9999, ...,  1163,  5220,   780], dtype=int16),
 (3480.0,
  -3600.0): array([-9999, -9999,  6201, ...,  1261,  4522,   660], dtype=int16),
 (3780.0,
  -4080.0): array([ 8432,  3221, -9999, ...,  1803,  5055,   742], dtype=int16),
 (5550.0,
  -3150.0): array([8481, 2158, 6329, ..., 1391, 4456,  686], dtype=int16),
 (5850.0,
  -5400.0): array([8219, 5023, 5509, ..., 1355, 4669,  671], dtype=int16),
 (4320.0,
 

In [25]:
len(assc)

10000

In [33]:
type(assc)

dict

In [32]:
assc[(4920.0, -5850.0)]

array([ 8315,  5289, -9999, ...,  1163,  5220,   780], dtype=int16)

In [22]:
blue_specs[0]

{'band_category': 'image',
 'band_long_name': 'band 2 surface reflectance',
 'band_name': 'sr_band2',
 'band_product': 'sr_refl',
 'band_short_name': 'LC8SR',
 'band_spectrum': [],
 'chip_x': 3000,
 'chip_y': -3000,
 'data_fill': -9999,
 'data_mask': {},
 'data_range': [-2000, 16000],
 'data_scale': 0.0001,
 'data_shape': [100, 100],
 'data_type': 'INT16',
 'data_units': None,
 'instrument': 'OLI_TIRS',
 'name': 'conus',
 'pixel_x': 30.0,
 'pixel_y': -30.0,
 'resample_method': None,
 'satellite': 'LANDSAT_8',
 'shift_x': 2415.0,
 'shift_y': -195.0,
 'tags': ['blue', ['LANDSAT', '8', 'OLI', 'TIRS', 'sr', 'band2']],
 'ubid': 'LANDSAT_8/OLI_TIRS/sr_band2',
 'wkt': 'PROJCS["Albers",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.2572221010042,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4269"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["standard_parallel_1",29.5],PARAMETE

In [23]:
blue_specs[1]

{'band_category': 'image',
 'band_long_name': 'band 1 surface reflectance',
 'band_name': 'sr_band1',
 'band_product': 'sr_refl',
 'band_short_name': 'LE7SR',
 'band_spectrum': [],
 'chip_x': 3000,
 'chip_y': -3000,
 'data_fill': -9999,
 'data_mask': {},
 'data_range': [-2000, 16000],
 'data_scale': 0.0001,
 'data_shape': [100, 100],
 'data_type': 'INT16',
 'data_units': None,
 'instrument': 'ETM',
 'name': 'conus',
 'pixel_x': 30.0,
 'pixel_y': -30.0,
 'resample_method': None,
 'satellite': 'LANDSAT_7',
 'shift_x': 2415.0,
 'shift_y': -195.0,
 'tags': ['blue', ['LANDSAT', '7', 'ETM', 'sr', 'band1']],
 'ubid': 'LANDSAT_7/ETM/sr_band1',
 'wkt': 'PROJCS["Albers",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.2572221010042,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4269"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["standard_parallel_1",29.5],PARAMETER["standard_parall